/* eslint-disable */
// Generated by Wrangler by running `wrangler types -c auxiliary/esbuild/wrangler.jsonc auxiliary/esbuild/worker-configuration.d.ts --no-include-runtime --env-interface EsbuildWorkerEnvironment` (hash: 2dd8b27991ba6d675c5fd9f403e7f0b8)
declare namespace CloudflareEsbuildWorker {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
	}
}
interface EsbuildWorkerEnvironment extends CloudflareEsbuildWorker.Env {}
