/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=auxiliary/esbuild/wrangler.jsonc --include-runtime=false --env-interface=EsbuildWorkerEnvironment auxiliary/esbuild/worker-configuration.d.ts` (hash: 62c2d8ff313e889dd719740a48e7413a)
interface __BaseEnv_EsbuildWorkerEnvironment {
}
declare namespace CloudflareEsbuildWorker {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_EsbuildWorkerEnvironment {}
}
interface EsbuildWorkerEnvironment extends __BaseEnv_EsbuildWorkerEnvironment {}
