/* eslint-disable */
// Generated by Wrangler by running `wrangler types -c auxiliary/esbuild/wrangler.jsonc auxiliary/esbuild/worker-configuration.d.ts --no-include-runtime --env-interface EsbuildWorkerEnvironment` (hash: 62c2d8ff313e889dd719740a48e7413a)
interface __BaseEnv_EsbuildWorkerEnvironment {
}
declare namespace CloudflareEsbuildWorker {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_EsbuildWorkerEnvironment {}
}
interface EsbuildWorkerEnvironment extends __BaseEnv_EsbuildWorkerEnvironment {}
