/**
 * Type declaration for the drizzle-kit generated migrations bundle.
 *
 * The actual implementation is in `migrations.js` (generated by drizzle-kit).
 * It imports `.sql` files as text strings and the journal JSON, producing
 * the `MigrationConfig` shape expected by `drizzle-orm/durable-sqlite/migrator`.
 */

declare const migrations: {
	journal: {
		entries: Array<{
			idx: number;
			when: number;
			tag: string;
			breakpoints: boolean;
		}>;
	};
	migrations: Record<string, string>;
};

export default migrations;
