/* eslint-disable */
// Generated by Wrangler by running `wrangler types -c auxiliary/email/wrangler.jsonc auxiliary/email/worker-configuration.d.ts --no-include-runtime --env-interface EmailWorkerEnvironment` (hash: 311c57b188d87a959fce3765dd06cf89)
interface __BaseEnv_EmailWorkerEnvironment {
	EMAIL: SendEmail;
	EMAIL_QUEUE: Queue;
	EMAIL_FROM: "Codemaxxing.ai <noreply@codemaxxing.ai>";
}
declare namespace CloudflareEmailWorker {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_EmailWorkerEnvironment {}
}
interface EmailWorkerEnvironment extends __BaseEnv_EmailWorkerEnvironment {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<CloudflareEmailWorker.Env, "EMAIL_FROM">> {}
}
