/* eslint-disable */
// Generated by Wrangler by running `wrangler types -c auxiliary/email/wrangler.jsonc auxiliary/email/worker-configuration.d.ts --no-include-runtime --env-interface EmailWorkerEnvironment` (hash: e269961a901a78ff45cd9ac388012fd4)
declare namespace CloudflareEmailWorker {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
		EMAIL_QUEUE: Queue;
		EMAIL_FROM: "Codemaxxing.ai <noreply@codemaxxing.ai>";
		RESEND_API_KEY: string;
	}
}
interface EmailWorkerEnvironment extends CloudflareEmailWorker.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<CloudflareEmailWorker.Env, "EMAIL_FROM" | "RESEND_API_KEY">> {}
}
