/* eslint-disable */
// Generated by Wrangler by running `wrangler types -c auxiliary/git/wrangler.jsonc auxiliary/git/worker-configuration.d.ts --no-include-runtime --env-interface GitWorkerEnvironment` (hash: 57eb212d0f12dbfb0a027fe4474a9d7b)
declare namespace CloudflareGitWorker {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "RepoDurableObject";
	}
	interface Env {
		REPO_BUCKET: R2Bucket;
		GIT_EVENTS: Queue;
		REPO_DO_IDLE_MINUTES: "30";
		REPO_DO_MAINT_MINUTES: "1440";
		REPO_KEEP_PACKS: "10";
		REPO_PACKLIST_MAX: "50";
		REPO_UNPACK_CHUNK_SIZE: "100";
		REPO_UNPACK_MAX_MS: "2000";
		REPO_UNPACK_DELAY_MS: "500";
		REPO_UNPACK_BACKOFF_MS: "1000";
		LOG_LEVEL: "info";
		JWT_PUBLIC_KEY: string;
		REPO_DO: DurableObjectNamespace<import("./index").RepoDurableObject>;
	}
}
interface GitWorkerEnvironment extends CloudflareGitWorker.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<CloudflareGitWorker.Env, "REPO_DO_IDLE_MINUTES" | "REPO_DO_MAINT_MINUTES" | "REPO_KEEP_PACKS" | "REPO_PACKLIST_MAX" | "REPO_UNPACK_CHUNK_SIZE" | "REPO_UNPACK_MAX_MS" | "REPO_UNPACK_DELAY_MS" | "REPO_UNPACK_BACKOFF_MS" | "LOG_LEVEL" | "JWT_PUBLIC_KEY">> {}
}
