/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=auxiliary/vite-host/wrangler.jsonc --include-runtime=false --env-interface=ViteHostWorkerEnvironment auxiliary/vite-host/worker-configuration.d.ts` (hash: 87fb8364a420e18fab3bd9160c2eaf64)
interface __BaseEnv_ViteHostWorkerEnvironment {
}
declare namespace CloudflareViteHostWorker {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_ViteHostWorkerEnvironment {}
}
interface ViteHostWorkerEnvironment extends __BaseEnv_ViteHostWorkerEnvironment {}
