/* eslint-disable */
// Generated by Wrangler by running `wrangler types -c auxiliary/push/wrangler.jsonc auxiliary/push/worker-configuration.d.ts --no-include-runtime --env-interface PushWorkerEnvironment` (hash: 559ac25f3499b0269dc2a5a2aa551bfa)
interface __BaseEnv_PushWorkerEnvironment {
	KV_PUSH_SUBSCRIPTION: KVNamespace;
	PUSH_QUEUE: Queue;
	VAPID_SUBJECT: "mailto:support@codemaxxing.ai";
	VAPID_PUBLIC_KEY: string;
	VAPID_PRIVATE_KEY: string;
}
declare namespace CloudflarePushWorker {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_PushWorkerEnvironment {}
}
interface PushWorkerEnvironment extends __BaseEnv_PushWorkerEnvironment {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<CloudflarePushWorker.Env, "VAPID_SUBJECT" | "VAPID_PUBLIC_KEY" | "VAPID_PRIVATE_KEY">> {}
}
