/* eslint-disable */
// Generated by Wrangler by running `wrangler types -c auxiliary/push/wrangler.jsonc auxiliary/push/worker-configuration.d.ts --no-include-runtime --env-interface PushWorkerEnvironment` (hash: a3c1442fe42eb490ff01c47a36e2daf1)
declare namespace CloudflarePushWorker {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
		KV_PUSH_SUBSCRIPTION: KVNamespace;
		PUSH_QUEUE: Queue;
		VAPID_SUBJECT: "mailto:support@codemaxxing.dev";
		VAPID_PUBLIC_KEY: string;
		VAPID_PRIVATE_KEY: string;
	}
}
interface PushWorkerEnvironment extends CloudflarePushWorker.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<CloudflarePushWorker.Env, "VAPID_SUBJECT" | "VAPID_PUBLIC_KEY" | "VAPID_PRIVATE_KEY">> {}
}
