/**
 * Plan Saver.
 *
 * Writes plan mode output to the .agent/plans/ directory and emits
 * a `plan_created` stream event. Cleans up old timestamped plans
 * to prevent unbounded growth.
 */

import fs from 'node:fs/promises';

import { planCreatedEvent } from './event-helpers';
import { cleanupTimestampPlans } from './session-cleanup';

import type { StreamEvent } from '@shared/agent-state';
import type { ModelMessage } from 'ai';

/**
 * Save plan content to disk and yield a plan_created event.
 *
 * @param projectRoot - Absolute path to the project root
 * @param planContent - The plan text generated by the agent
 * @param messages - Conversation messages (used to derive the plan header)
 */
export async function* savePlan(projectRoot: string, planContent: string, messages: ModelMessage[]): AsyncIterable<StreamEvent> {
	try {
		const plansDirectory = `${projectRoot}/.agent/plans`;
		await fs.mkdir(plansDirectory, { recursive: true });

		const timestamp = Date.now();
		const planFileName = `${timestamp}-plan.md`;
		const planPath = `${plansDirectory}/${planFileName}`;

		// Derive prompt text from the first user message
		const firstUserMessage = messages.find((m) => m.role === 'user');
		const promptText = typeof firstUserMessage?.content === 'string' ? firstUserMessage.content : '';
		const header = `# Plan: ${promptText.slice(0, 80)}${promptText.length > 80 ? '...' : ''}\n\n_Generated at ${new Date(timestamp).toISOString()}_\n\n---\n\n`;
		await fs.writeFile(planPath, header + planContent);

		// Clean up old timestamped plans to prevent unbounded growth
		await cleanupTimestampPlans(projectRoot);

		yield planCreatedEvent(`/.agent/plans/${planFileName}`);
	} catch (error) {
		console.error('Failed to save plan:', error);
	}
}
