/**
 * Protected file guard for AI agent tools.
 *
 * Returns file-specific NOT_ALLOWED errors when the agent tries to modify
 * IDE-managed system files. Messages are formatted for LLM consumption.
 */

import { PROTECTED_SYSTEM_FILES } from '@shared/constants';
import { ToolErrorCode, toolError } from '@shared/tool-errors';

import type { ProtectedSystemFile } from '@shared/constants';

function isProtectedSystemFile(path: string): path is ProtectedSystemFile {
	return PROTECTED_SYSTEM_FILES.has(path);
}

const PROTECTED_FILE_MESSAGES: Record<ProtectedSystemFile, string> = {
	'/package.json':
		'Cannot edit /package.json directly — this file is managed by the IDE. Use the dependencies_list tool to view current dependencies and the dependencies_update tool to add, remove, or update packages.',
	'/wrangler.jsonc':
		'Cannot edit /wrangler.jsonc directly — this file is managed by the IDE. Use the asset_settings_get tool to view current settings and the asset_settings_update tool to change asset routing configuration. Use the bindings_get/bindings_update tools to manage bindings.',
	'/vite.config.ts':
		'Cannot edit /vite.config.ts — this file is auto-generated by the IDE based on project dependencies and cannot be modified directly.',
	'/vitest.config.ts':
		'Cannot edit /vitest.config.ts — this file is auto-generated by the IDE based on project settings and cannot be modified directly.',
	'/worker-env.d.ts':
		'Cannot edit /worker-env.d.ts — this file is auto-generated by the IDE based on enabled bindings. Use the bindings_get tool to view current bindings and the bindings_update tool to enable or disable bindings.',
};

/**
 * If the given path is a protected system file, throw a NOT_ALLOWED error
 * with an LLM-friendly message explaining the correct tool to use.
 *
 * Call this early in any tool that writes, edits, or fixes files.
 * Returns normally when the path is not protected.
 */
export function guardProtectedFile(path: string): void {
	if (!isProtectedSystemFile(path)) return;

	toolError(ToolErrorCode.NOT_ALLOWED, PROTECTED_FILE_MESSAGES[path]);
}
