/* eslint-disable */
// Generated by Wrangler by running `wrangler types -c auxiliary/biome/wrangler.jsonc auxiliary/biome/worker-configuration.d.ts --no-include-runtime --env-interface BiomeWorkerEnvironment` (hash: fbafefd929bb42748a91d3cff6e56ad2)
declare namespace CloudflareBiomeWorker {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
	}
}
interface BiomeWorkerEnvironment extends CloudflareBiomeWorker.Env {}
