/* eslint-disable */
// Generated by Wrangler by running `wrangler types -c auxiliary/biome/wrangler.jsonc auxiliary/biome/worker-configuration.d.ts --no-include-runtime --env-interface BiomeWorkerEnvironment` (hash: 34faff7ec23434f1c281d65ff60760c2)
interface __BaseEnv_BiomeWorkerEnvironment {
}
declare namespace CloudflareBiomeWorker {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_BiomeWorkerEnvironment {}
}
interface BiomeWorkerEnvironment extends __BaseEnv_BiomeWorkerEnvironment {}
