/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=auxiliary/biome/wrangler.jsonc --include-runtime=false --env-interface=BiomeWorkerEnvironment auxiliary/biome/worker-configuration.d.ts` (hash: 34faff7ec23434f1c281d65ff60760c2)
interface __BaseEnv_BiomeWorkerEnvironment {
}
declare namespace CloudflareBiomeWorker {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_BiomeWorkerEnvironment {}
}
interface BiomeWorkerEnvironment extends __BaseEnv_BiomeWorkerEnvironment {}
