/**
 * Worker-specific type definitions.
 *
 * The `Env` interface is auto-generated by `bunx wrangler types`
 * into `worker-configuration.d.ts` and available globally.
 */

/**
 * Hono app environment type with custom variables.
 */
export interface AppEnvironment {
	Bindings: Env;
	Variables: {
		projectId: string;
		projectRoot: string;
		fsStub: ReturnType<Env['DO_FILESYSTEM']['get']>;
	};
}
