/**
 * Worker-specific type definitions.
 *
 * The `Env` interface is auto-generated by `bunx wrangler types`
 * into `worker-configuration.d.ts` and available globally.
 *
 * Environment variables and service bindings are accessed via
 * `import { env, exports } from 'cloudflare:workers'` rather than
 * through the Hono context `c.env`. Durable Object namespaces live
 * on `exports` (e.g. `exports.DurableObjectFilesystem`).
 */

import type { ExpiringFilesystem } from './durable/expiring-filesystem';

/**
 * Hono app environment type with custom variables.
 */
export interface AppEnvironment {
	Bindings: Env;
	Variables: {
		projectId: string;
		projectRoot: string;
		fsStub: DurableObjectStub<ExpiringFilesystem>;
	};
}
