/**
 * Worker-specific type definitions.
 *
 * The `Env` interface is auto-generated by `bunx wrangler types`
 * into `worker-configuration.d.ts` and available globally.
 *
 * Environment variables and service bindings are accessed via
 * `import { env, exports } from 'cloudflare:workers'` rather than
 * through the Hono context `c.env`. Durable Object namespaces live
 * on `exports` (e.g. `exports.DurableObjectFilesystem`).
 */

import type { ProjectFilesystem } from './durable/project-filesystem';

/**
 * Base auth variables set by the auth middleware on all protected routes.
 */
interface AuthVariables {
	userId: string;
	userSession: { id: string; activeOrganizationId?: string | null | undefined };
	activeOrganizationId: string | undefined;
}

/**
 * Hono environment for routes that only require authentication (no project context).
 * Used by root-level API routes like /api/new-project, /api/org/*.
 */
export interface AuthedEnvironment {
	Bindings: Env;
	Variables: AuthVariables;
}

/**
 * Hono app environment type with auth + project-scoped variables.
 * Used by all /p/:projectId/api/* route handlers.
 */
export interface AppEnvironment {
	Bindings: Env;
	Variables: AuthVariables & {
		projectId: string;
		projectRoot: string;
		fsStub: DurableObjectStub<ProjectFilesystem>;
	};
}
