/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=auxiliary/vite-host-deploy/wrangler.jsonc --include-runtime=false --env-interface=ViteHostDeployWorkerEnvironment auxiliary/vite-host-deploy/worker-configuration.d.ts` (hash: a3f5d514c33b867c18c522b74daac6d6)
interface __BaseEnv_ViteHostDeployWorkerEnvironment {
}
declare namespace CloudflareViteHostDeployWorker {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_ViteHostDeployWorkerEnvironment {}
}
interface ViteHostDeployWorkerEnvironment extends __BaseEnv_ViteHostDeployWorkerEnvironment {}
